### ISSUE TITLE
UnsignedInt, hexBinary and Co.

### ISSUE THREAD

**Issue by PiQ99** [fnogatz/xsd2json#17]
Hey guy,

at first thanks for working on my issue. Nevertheless I have the question, if you could add support for xs:unsignedInt. 

Would it be possible, to add the entry type to every json-object, nevertheless if you can resolve the type? 
Example: 
If the type is xs:unsignedInt and you are not able to resolve it, you can just add
"element" : {
 "type" :"unsignedInt",
 "description" :"whatever"
} 

Maybe you already added this support, but atm I am at version 1.0.1 because with version 1.2.1 the generation of json-schema-files is not working anymore. Is there a way for me, to debug the process or to help finding the error on my xsd-files or your process?

Atm you dont entry an entry for the type-field instead, right?

Thanks in advance,
PiQ99

**Comment by fnogatz** [comment]
I have added all primitive XSD types by 7ea0cebee09c532247d2f2ed1903da76af58324f and 9dd6d7a96176c4beeceb9cee82cc7e57add80588.
