### ISSUE TITLE
Error for xsd to json

### ISSUE THREAD

**Issue by mailuser41** [fnogatz/xsd2json#22]
I get this error:

stack": [
    "Error: spawn swipl ENOENT",
    "    at exports._errnoException (util.js:746:11)",
    "    at Process.ChildProcess._handle.onexit (child_process.js:1053:32)",
    "    at child_process.js:1144:20",
    "    at process._tickDomainCallback (node.js:381:11)",
    "    at process.<anonymous> (/home/syedn/proj/ori/propfi/node_modules/loopback/node_modules/continuation-local-storage/node_modules/async-listener/index.js:18:15)"
  ],
  "level": "error",
  "message": "uncaughtException: spawn swipl ENOENT"

**Comment by fnogatz** [comment]
Could you please provide more details? What are you trying to do? Are you using die CLI or programmatically with node.js? Is it possible to share your tested XSD file?

**Comment by mailuser41** [comment]
This got resolved after installing swipl. Thanks
