### ISSUE TITLE
xsd2json error

### ISSUE THREAD

**Issue by maximprokopenko** [fnogatz/xsd2json#36]
> xsd2json
/usr/local/bin/xsd2json: 3: exec: /home/fnogatz/.swivm/versions/7.2.3/lib/swipl-7.2.3/bin/x86_64-linux/swipl: not found

What is "/home/fnogatz/.swivm/versions/7.2.3/lib/swipl-7.2.3/bin/x86_64-linux/swipl" ?

**Comment by fnogatz** [comment]
So, after adding and removing SWI-Prolog's `stand_alone` flag I had to realize it is not that easy to deploy Prolog code for users that do not have SWI-Prolog installed. So I finally moved the creation of the qlf files (precompiled SWI-Prolog files which are machine-dependent, as you noticed) to user-land, i.e. the qlf file is created at `postinstall`.

The updated version is `1.7.3` and published on npm. Please verify it is working for you now.
