### ISSUE TITLE
Question about loss

### ISSUE THREAD

**Issue by kirankashalkar** [fnogatz/xsd2json#37]
Does this tool convert losslessly from XSD to JSON-schema?

**Comment by fnogatz** [comment]
Is this even possible?

**Comment by fnogatz** [comment]
Some of the elements that are not yet converted are listed in the section "4 Conclusion" of the [CHR Workshop paper](http://arxiv.org/pdf/1406.2125v1.pdf) and in the BSc Thesis [here](http://www.informatik.uni-ulm.de/pm/fileadmin/pm/home/fruehwirth/drafts/Bsc-Nogatz.pdf) (p. 54).

**Comment by fnogatz** [comment]
I'm closing here. Let me know when you have a concrete example what gets lost in the current version and I'm open to fix it :)
