### ISSUE TITLE
Validation after conversion

### ISSUE THREAD

**Issue by rajashekhargundeti** [fnogatz/xsd2json#39]
Hi,

I need to do xml validation against xsd. i thought of using libxmljs module. i couldn't move forward with it as it has some building/installation issues. Moreover, i haven't found any other module to accomplish the task.

Now, i would like to use xsd2json converter to convert XSD to JSON and XML to JSON and validate it.

Please let me know if there is already a validator for this. or how do you suggest me to go about this.

Thanks,
Raja

**Comment by fnogatz** [comment]
In general it does not seem like the perfect idea to convert both formats first only to execute the validation with JSON and JSON Schema. Both conversions will not be without some loss, and even worse, this xsd2json tool might use other assumptions to translate the schema than some other tool uses to translate the XML file to JSON. I would stick to existing XSD validators.

**Comment by rajashekhargundeti** [comment]
I dont find anything otherthan libxmljs

**Comment by fnogatz** [comment]
Have a look at the [Apache Xerces Project](http://xerces.apache.org/). It is great for validating XML documents against XML Schema.

**Comment by rajashekhargundeti** [comment]
I think, it is in java, not javascript, right??

**Comment by fnogatz** [comment]
I am not aware of JavaScript validators for XML Schema. Apache Xerces is indeed available for Java and C.

**Comment by fnogatz** [comment]
I will close here. Feel free to re-open in case you need any help with xsd2json.
