### ISSUE TITLE
Syntax errors

### ISSUE THREAD

**Issue by albanm** [fnogatz/xsd2json#6]
Hello again :)

When running cli.pl I encounter the following errors:

ERROR: c:/users/mouton-a/sandbox/git/xsd2json/prolog-xsd2json/merge_json.pl:60:14: Syntax error: Operator expected
ERROR: c:/users/mouton-a/sandbox/git/xsd2json/prolog-xsd2json/xsd2json.pl:380:12: Syntax error: Operator expected
ERROR: c:/users/mouton-a/sandbox/git/xsd2json/prolog-xsd2json/xsd2json.pl:381:11: Syntax error: Operator expected

Most of the times this is non-blocking. But on some XSDs it is followed by the blocking error:

ERROR: c:/users/mouton-a/sandbox/git/xsd2json/prolog-xsd2json/cli.pl:5: Initialization goal raised exception:
ERROR: xsd2json:convert_xsd_restriction/3: Undefined procedure: xsd2json:json_false/1

The 3 lines contain arobases. Coincidence ? I think not !

Wondering if this could be an encoding problem I tried adding ':- encoding(utf8).' to the source files. But it didn't fix anything and being totally ignorant of prolog I am already out of ideas.

Environment:

```
$ swipl -v
SWI-Prolog version 6.6.6 for i386-win32
```

**Comment by gabrielmancini** [comment]
me too

**Comment by fnogatz** [comment]
Could you please provide your error messages, @gabrielmancini? This issue is two years old, the codebase has changed since then :)
