### ISSUE TITLE
Type error: `atomic' expected, found `ns(xs,'http://www.w3.org/2001/XMLSchema'):'NCName''

### ISSUE THREAD

**Issue by khusamov** [fnogatz/xsd2json#68]
```
C:\Temp>xsd2json XMLSchema2.xsd > temp.json
ERROR: -g user:main: string_concat/3: Type error: `atomic' expected, found `ns(xs,'http://www.w3.org/2001/XMLSchema'):'NCName'' (a compound)
```

**Comment by fnogatz** [comment]
As before in #67: There are other issues regarding xsd2json's full compliance to the XML Schema standard. Because we are not ready yet, the XML Meta-Schemas in the `/test` directory can not be translated out-of-the-box. However, the `xsd2json` CLI should work with any file located at `/test/xsd`.
