### ISSUE TITLE
Keep getting error running example from doc - update

### ISSUE THREAD

**Issue by Heucles** [fnogatz/xsd2json#77]
@fnogatz just updated to version 7.6.3, but also rebuilded the package, but I am still facing the same issues as in https://github.com/fnogatz/xsd2json/issues/76 .Any Ideas?

**Comment by fnogatz** [comment]
Hm, what happens if you go into `/node_modules/xsd2json` and run `npm run test-cli`?

**Comment by fnogatz** [comment]
I simply can not reproduce this bug report. The versions **v7.6.x` of SWI-Prolog should work as expected. Please provide more information on this bug as requested before.
